/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

// Reads content/blog/*.md (YAML frontmatter + Markdown body), renders each to
// HTML, and writes a single generated TS module (src/data/blog-posts.generated.ts,
// gitignored) that both BlogPostPage.tsx/BlogIndexPage.tsx and scripts/prerender.ts
// import. Parsing happens once here, at build time in Node — no Markdown parser
// ships in the client bundle. Run before `vite build` (see package.json).
//
// Adding a post = drop a new .md file in content/blog/ with the same frontmatter
// shape and re-run the build. No JSX, no CMS.

import fs from "fs";
import path from "path";
import matter from "gray-matter";
import { marked } from "marked";

interface BlogPostFrontmatter {
  title: string;
  slug: string;
  date: string;
  /** Optional "YYYY-MM-DD" of the last substantive edit; drives sitemap lastmod + dateModified. */
  updated?: string;
  excerpt: string;
  metaDescription: string;
  tags: string[];
}

interface GeneratedBlogPost extends BlogPostFrontmatter {
  contentHtml: string;
}

const contentDir = path.join(process.cwd(), "content", "blog");
const outPath = path.join(process.cwd(), "src", "data", "blog-posts.generated.ts");

if (!fs.existsSync(contentDir)) {
  console.error(`generate-blog-data: ${contentDir} not found.`);
  process.exit(1);
}

const files = fs.readdirSync(contentDir).filter((file) => file.endsWith(".md"));

const posts: GeneratedBlogPost[] = files.map((file) => {
  const raw = fs.readFileSync(path.join(contentDir, file), "utf-8");
  const { data, content } = matter(raw);
  const frontmatter = data as BlogPostFrontmatter;

  for (const field of ["title", "slug", "date", "excerpt", "metaDescription", "tags"] as const) {
    if (frontmatter[field] === undefined) {
      console.error(`generate-blog-data: ${file} is missing required frontmatter field "${field}".`);
      process.exit(1);
    }
  }

  const contentHtml = marked.parse(content, { async: false }) as string;
  return { ...frontmatter, contentHtml };
});

posts.sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));

const slugs = new Set<string>();
for (const post of posts) {
  if (slugs.has(post.slug)) {
    console.error(`generate-blog-data: duplicate slug "${post.slug}".`);
    process.exit(1);
  }
  slugs.add(post.slug);
}

const fileContents = `// AUTO-GENERATED by scripts/generate-blog-data.ts — do not edit by hand.
// Source: content/blog/*.md — edit those files and re-run \`npm run build\` (or
// \`npx tsx scripts/generate-blog-data.ts\` directly during local development).

export interface BlogPost {
  title: string;
  slug: string;
  date: string;
  /** Optional "YYYY-MM-DD" of the last substantive edit; drives sitemap lastmod + dateModified. */
  updated?: string;
  excerpt: string;
  metaDescription: string;
  tags: string[];
  contentHtml: string;
}

export const blogPosts: BlogPost[] = ${JSON.stringify(posts, null, 2)};

export function getBlogPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((post) => post.slug === slug);
}
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, fileContents, "utf-8");
console.log(`generate-blog-data: wrote ${posts.length} post(s) to ${path.relative(process.cwd(), outPath)}`);
